name             'lamp'
maintainer       'Daft Labs'
maintainer_email 'support@daftlabs.com'
license          'All rights reserved'
description      'Installs/Configures a LAMP server.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.16.0'

depends 'apt'
depends 'ark'
depends 'curl'
depends 'java'
depends 'php'
depends 'apache2'
depends 'mysql'
depends 'composer'
depends 'tests'
depends 'apache2'
